# Generated by Django 3.2.9 on 2021-12-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211202_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
    ]
