# Generated by Django 3.2.9 on 2021-12-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
