# Generated by Django 3.2.9 on 2021-12-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Nickname', max_length=100),
            preserve_default=False,
        ),
    ]
